name: Terraform Apply

on:
    push:
        branches:
            - main

jobs:
    install_deps:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Node.js and npm
              uses: actions/setup-node@v2
              with:
                  node-version: "16.x"

            - name: Install dependencies for Assets Handler Lambda
              working-directory: "Assets Handler Lambda"
              run: npm install

            - name: Install dependencies for Failure Report Handler Lambda
              working-directory: "Failure Report Handler Lambda"
              run: npm install

    terraform:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.5.4

            - name: Initialize Terraform
              id: Initialize
              run: terraform init

            - name: Terraform Plan
              id: plan
              run: terraform plan -no-color -var "access_key=${AWS_ACCESS_KEY_ID}" -var "secret_key=${AWS_SECRET_ACCESS_KEY}" -var "region=${AWS_REGION}"

            - name: Terraform Apply
              run: terraform apply -auto-approve -var "access_key=${AWS_ACCESS_KEY_ID}" -var "secret_key=${AWS_SECRET_ACCESS_KEY}" -var "region=${AWS_REGION}"
